### ISSUE TITLE
Get listed on the FMI tools page 

### ISSUE THREAD

**Issue by chrbertsch** [dnv-opensource/mlfmu#77]
Great work!
Please list your toolbox on https://fmi-standard.org/tools/ , see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list how to add your tool.

**Comment by chrbertsch** [comment]
Thanks to adding your tool on the FMI tools page. 

As https://github.com/dnv-opensource/mlfmu/tree/main/examples is linked from [Examples & Compatibility](https://github.com/dnv-opensource/mlfmu/tree/main/examples) there:
please 
- provide information with which validation tools from [https://fmi-standard.org/validation/](https://fmi-standard.org/validation/) and other importing tools you have tested the FMUs
- provide the built FMUs with binaries

**Comment by StephanieKemna** [comment]
Remaining tasks:

- [ ] Add FMU binaries 
- [ ] Add README for https://github.com/dnv-opensource/mlfmu/tree/main/examples to refer to docs, FMU file locations, and validation tools used.

**Comment by StephanieKemna** [comment]
> @StephanieKemna : Thanks for adding the Readme. Pleas note that FMUcheck does only a static validation of the FMU, it would be great to use also the other tools listed on https://fmi-standard.org/validation/ (fmpy or fmusim from the Reference FMUs) to simulate the FMUs, and add this information to the Readme.

Thanks @chrbertsch - we can have a look at this (might be after the winter holidays). I will check about the STC url now.
